model_ci_test_config_list:
  - NAME: "tiny-random-qwen3"
    AISTUDIO_REPO_ID: "PaddleFormers/tiny-random-qwen3"
    MODEL_NAME_OR_PATH: "./models/tiny-random-qwen3"
    MAX_STEPS: 5
    SAVE_STEPS: 3
    DPO_TRAIN_DATASET_PATH: "./tests/fixtures/dummy/ernie/dpo-train.jsonl"
    DPO_EVAL_DATASET_PATH: "./tests/fixtures/dummy/ernie/dpo-train.jsonl"
    DPO_FC_TRAIN_DATASET_PATH: "./tests/fixtures/dummy/ernie/dpo-train.jsonl"
    DPO_FC_EVAL_DATASET_PATH: "./tests/fixtures/dummy/ernie/dpo-train.jsonl"
    DPO_FULL_EXCEPTED_LOSS: 0.692086
    DPO_FULL_REUSME_EXCEPTED_LOSS: 0.691044
    DPO_FULL_EXPECTED_RESULT:
      - [22407, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612]
    DPO_LORA_EXCEPTED_LOSS: 0.692095
    DPO_LORA_REUSME_EXCEPTED_LOSS: 0.691209
    DPO_LORA_EXPECTED_RESULT:
      - [22407, 120525, 77505, 113631, 47887, 134141, 122487, 61092, 40897, 40601]
    DPO_FULL_TP_PP_EXCEPTED_LOSS: 0.692381
    DPO_FULL_TP_PP_REUSME_EXCEPTED_LOSS: 0.691568
    DPO_FULL_TP_PP_EXPECTED_RESULT:
      - [22407, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612]
    DPO_LORA_TP_PP_EXCEPTED_LOSS: 0.692254
    DPO_LORA_TP_PP_REUSME_EXCEPTED_LOSS: 0.691406
    DPO_LORA_TP_PP_EXPECTED_RESULT:
      - [22407, 120525, 77505, 113631, 47887, 134141, 122487, 61092, 40897, 40601]
    DPO_FC_EXCEPTED_LOSS: 0.692086
    DPO_FC_REUSME_EXCEPTED_LOSS: 0.691044
    DPO_FC_EXPECTED_RESULT:
      - [22407, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612]
    SFT_TRAIN_DATASET_PATH: "./tests/fixtures/dummy/ernie/sft-train.jsonl"
    SFT_EVAL_DATASET_PATH: "./tests/fixtures/dummy/ernie/sft-train.jsonl"
    SFT_FC_TRAIN_DATASET_PATH: "./tests/fixtures/dummy/function-call/function-call-train.jsonl"
    SFT_FC_EVAL_DATASET_PATH: "./tests/fixtures/dummy/function-call/function-call-eval.jsonl"
    SFT_FULL_EXCEPTED_LOSS: 11.931005
    SFT_FULL_REUSME_EXCEPTED_LOSS: 11.920915
    SFT_FULL_EXPECTED_RESULT:
      - [22407, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612]
    SFT_LORA_EXCEPTED_LOSS: 11.94409
    SFT_LORA_REUSME_EXCEPTED_LOSS: 11.943027
    SFT_LORA_EXPECTED_RESULT:
      - [22407, 120525, 77505, 113631, 47887, 134141, 122487, 61092, 40897, 40601]
    SFT_FULL_TP_PP_EXCEPTED_LOSS: 11.945682
    SFT_FULL_TP_PP_REUSME_EXCEPTED_LOSS: 11.938123
    SFT_FULL_TP_PP_EXPECTED_RESULT:
      - [22407, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612]
    SFT_LORA_TP_PP_EXCEPTED_LOSS: 11.94778
    SFT_LORA_TP_PP_REUSME_EXCEPTED_LOSS: 11.941195
    SFT_LORA_TP_PP_EXPECTED_RESULT:
      - [22407, 120525, 77505, 113631, 47887, 134141, 122487, 61092, 40897, 11806]
    SFT_FC_EXCEPTED_LOSS: 11.945908
    SFT_FC_REUSME_EXCEPTED_LOSS: 11.939684
    SFT_FC_EXPECTED_RESULT:
      - [22407, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612]
    PT_TRAIN_DATASET_PATH: "./tests/fixtures/dummy/ernie/pt-train.jsonl"
    PT_EVAL_DATASET_PATH: "./tests/fixtures/dummy/ernie/pt-train.jsonl"
    PT_FC_TRAIN_DATASET_PATH: "./tests/fixtures/dummy/function-call/function-call-train.jsonl"
    PT_FC_EVAL_DATASET_PATH: "./tests/fixtures/dummy/function-call/function-call-eval.jsonl"
    PT_FULL_EXCEPTED_LOSS: 11.931005
    PT_FULL_REUSME_EXCEPTED_LOSS: 11.920915
    PT_FULL_EXPECTED_RESULT:
      - [22407, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612]
    PT_LORA_EXCEPTED_LOSS: 11.94409
    PT_LORA_REUSME_EXCEPTED_LOSS: 11.943027
    PT_LORA_EXPECTED_RESULT:
      - [22407, 120525, 77505, 113631, 47887, 134141, 122487, 61092, 40897, 40601]
    PT_FULL_TP_PP_EXCEPTED_LOSS: 11.945682
    PT_FULL_TP_PP_REUSME_EXCEPTED_LOSS: 11.938123
    PT_FULL_TP_PP_EXPECTED_RESULT:
      - [22407, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612]
    PT_LORA_TP_PP_EXCEPTED_LOSS: 11.94778
    PT_LORA_TP_PP_REUSME_EXCEPTED_LOSS: 11.941195
    PT_LORA_TP_PP_EXPECTED_RESULT:
      - [22407, 120525, 77505, 113631, 47887, 134141, 122487, 61092, 40897, 11806]
    PT_FC_EXCEPTED_LOSS: 11.945908
    PT_FC_REUSME_EXCEPTED_LOSS: 11.939684
    PT_FC_EXPECTED_RESULT:
      - [22407, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612]
  - NAME: "tiny-random-qwen3moe"
    AISTUDIO_REPO_ID: "PaddleFormers/tiny-random-qwen3moe"
    MODEL_NAME_OR_PATH: "./models/tiny-random-qwen3moe"
    MAX_STEPS: 5
    SAVE_STEPS: 3
    DPO_TRAIN_DATASET_PATH: "./tests/fixtures/dummy/ernie/dpo-train.jsonl"
    DPO_EVAL_DATASET_PATH: "./tests/fixtures/dummy/ernie/dpo-train.jsonl"
    DPO_FC_TRAIN_DATASET_PATH: "./tests/fixtures/dummy/ernie/dpo-train.jsonl"
    DPO_FC_EVAL_DATASET_PATH: "./tests/fixtures/dummy/ernie/dpo-train.jsonl"
    DPO_FULL_EXCEPTED_LOSS: 0.692086
    DPO_FULL_REUSME_EXCEPTED_LOSS: 0.691044
    DPO_FULL_EXPECTED_RESULT:
      - [22407, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612]
    DPO_LORA_EXCEPTED_LOSS: 0.692095
    DPO_LORA_REUSME_EXCEPTED_LOSS: 0.691209
    DPO_LORA_EXPECTED_RESULT:
      - [22407, 120525, 77505, 113631, 47887, 134141, 122487, 61092, 40897, 40601]
    DPO_FULL_TP_PP_EXCEPTED_LOSS: 0.692381
    DPO_FULL_TP_PP_REUSME_EXCEPTED_LOSS: 0.691568
    DPO_FULL_TP_PP_EXPECTED_RESULT:
      - [22407, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612]
    DPO_LORA_TP_PP_EXCEPTED_LOSS: 0.692254
    DPO_LORA_TP_PP_REUSME_EXCEPTED_LOSS: 0.691406
    DPO_LORA_TP_PP_EXPECTED_RESULT:
      - [22407, 120525, 77505, 113631, 47887, 134141, 122487, 61092, 40897, 40601]
    DPO_FC_EXCEPTED_LOSS: 0.692086
    DPO_FC_REUSME_EXCEPTED_LOSS: 0.691044
    DPO_FC_EXPECTED_RESULT:
      - [22407, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612]
    SFT_TRAIN_DATASET_PATH: "./tests/fixtures/dummy/ernie/sft-train.jsonl"
    SFT_EVAL_DATASET_PATH: "./tests/fixtures/dummy/ernie/sft-train.jsonl"
    SFT_FC_TRAIN_DATASET_PATH: "./tests/fixtures/dummy/function-call/function-call-train.jsonl"
    SFT_FC_EVAL_DATASET_PATH: "./tests/fixtures/dummy/function-call/function-call-eval.jsonl"
    SFT_FULL_EXCEPTED_LOSS: 11.931005
    SFT_FULL_REUSME_EXCEPTED_LOSS: 11.920915
    SFT_FULL_EXPECTED_RESULT:
      - [22407, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612]
    SFT_LORA_EXCEPTED_LOSS: 11.94409
    SFT_LORA_REUSME_EXCEPTED_LOSS: 11.943027
    SFT_LORA_EXPECTED_RESULT:
      - [22407, 120525, 77505, 113631, 47887, 134141, 122487, 61092, 40897, 40601]
    SFT_FULL_TP_PP_EXCEPTED_LOSS: 11.945682
    SFT_FULL_TP_PP_REUSME_EXCEPTED_LOSS: 11.938123
    SFT_FULL_TP_PP_EXPECTED_RESULT:
      - [22407, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612]
    SFT_LORA_TP_PP_EXCEPTED_LOSS: 11.94778
    SFT_LORA_TP_PP_REUSME_EXCEPTED_LOSS: 11.941195
    SFT_LORA_TP_PP_EXPECTED_RESULT:
      - [22407, 120525, 77505, 113631, 47887, 134141, 122487, 61092, 40897, 11806]
    SFT_FC_EXCEPTED_LOSS: 11.945908
    SFT_FC_REUSME_EXCEPTED_LOSS: 11.939684
    SFT_FC_EXPECTED_RESULT:
      - [22407, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612]
    PT_TRAIN_DATASET_PATH: "./tests/fixtures/dummy/ernie/pt-train.jsonl"
    PT_EVAL_DATASET_PATH: "./tests/fixtures/dummy/ernie/pt-train.jsonl"
    PT_FC_TRAIN_DATASET_PATH: "./tests/fixtures/dummy/function-call/function-call-train.jsonl"
    PT_FC_EVAL_DATASET_PATH: "./tests/fixtures/dummy/function-call/function-call-eval.jsonl"
    PT_FULL_EXCEPTED_LOSS: 11.931005
    PT_FULL_REUSME_EXCEPTED_LOSS: 11.920915
    PT_FULL_EXPECTED_RESULT:
      - [22407, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612]
    PT_LORA_EXCEPTED_LOSS: 11.94409
    PT_LORA_REUSME_EXCEPTED_LOSS: 11.943027
    PT_LORA_EXPECTED_RESULT:
      - [22407, 120525, 77505, 113631, 47887, 134141, 122487, 61092, 40897, 40601]
    PT_FULL_TP_PP_EXCEPTED_LOSS: 11.945682
    PT_FULL_TP_PP_REUSME_EXCEPTED_LOSS: 11.938123
    PT_FULL_TP_PP_EXPECTED_RESULT:
      - [22407, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612]
    PT_LORA_TP_PP_EXCEPTED_LOSS: 11.94778
    PT_LORA_TP_PP_REUSME_EXCEPTED_LOSS: 11.941195
    PT_LORA_TP_PP_EXPECTED_RESULT:
      - [22407, 120525, 77505, 113631, 47887, 134141, 122487, 61092, 40897, 11806]
    PT_FC_EXCEPTED_LOSS: 11.945908
    PT_FC_REUSME_EXCEPTED_LOSS: 11.939684
    PT_FC_EXPECTED_RESULT:
      - [22407, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612, 90612]